### ISSUE TITLE
Demo Script

### ISSUE THREAD

**Issue by anas-zafar** [QitaoZhao/PoseFormerV2#1]
Thank you for the amazing work! Can you please share the demo script to run on the wild videos? Thanks

**Comment by QitaoZhao** [comment]
Thanks for your interest in our work. We follow [MHFormer](https://github.com/Vegetebird/MHFormer) to prepare our video demo. I will make it clear in README.

**Comment by 258ljy** [comment]
我想知道这个野外视频哪里来的呢？？

**Comment by QitaoZhao** [comment]
Hi, 我们应该是在YouTube上找的。
