### ISSUE TITLE
About camera intrinsics and inference

### ISSUE THREAD

**Issue by RHnejad** [QitaoZhao/PoseFormerV2#10]
Thank you for sharing the code.

May I ask whether the camera intrinsics have been used for preprocessing the data (assuming that we have access to 2D gt in pixel space)? According to my understanding even though you are returning them with "out_camera_params" they have not been used in the scripts so I just wanted to ask whether there is any other place where they might be needed. 

I also wanted to ask about your recommended 2D pose estimator for running your code for inference and whether there is a plan to provide an inference script in the future. 

Thanks in advance for your time.

**Comment by QitaoZhao** [comment]
Thanks for your interest! You are right. We do not use camera intrinsics for data pre-processing. We may clean the code for clarity.

You can refer to [MHFormer](https://github.com/Vegetebird/MHFormer) to prepare your video demo, and they use HRNet. We may release the script for in-the-wild inference in the future.

**Comment by QitaoZhao** [comment]
You can also check [poseformer_demo](https://github.com/zczcwh/poseformer_demo).
