### ISSUE TITLE
Able to run realtime?

### ISSUE THREAD

**Issue by Yuanhong200727** [QitaoZhao/PoseFormerV2#11]
Great work!I am wondering can the model run real-time with video stream input?
Thanks!

**Comment by QitaoZhao** [comment]
Thanks for your comments. As we use a 2D pose sequence as input, where some elements are from the "future", the current method is not suitable for running in real-time. You may refer to [VideoPose3D](https://github.com/facebookresearch/VideoPose3D), and they may provide the causal model to solve the issue above.
