### ISSUE TITLE
python3.8 error

### ISSUE THREAD

**Issue by PMPBinZhang** [QitaoZhao/PoseFormerV2#13]
when pip install -r requirements.txt, some pkgs need python 3.9. the python of your project is python3.8?

**Comment by QitaoZhao** [comment]
It seems weird. You may try just to run the code and install new packages when required.

**Comment by JiaweiMorris** [comment]
一样的问题，不兼容的包有ipython、matplotlib、networkx、numpy等，安装log：
  Link requires a different Python (3.8.18 not in: '>=3.9'): https://pypi.tuna.tsinghua.edu.cn/packages/d0/b2/fe774844d1857804cc884bba67bec38f649c99d0dc1ee7cbbf1da601357c/numpy-1.25.0.tar.gz#sha256=f1accae9a28dc3cda46a91de86acf69de0d1b5f
4edd44a9b0c3ceb8036dfff19 (from https://pypi.tuna.tsinghua.edu.cn/simple/numpy/) (requires-python:>=3.9)

并且还有的包对应版本不存在
ERROR: Could not find a version that satisfies the requirement ruamel-yaml-conda==0.15.100 (from versions: 0.15.80)
ERROR: Could not find a version that satisfies the requirement setuptools==52.0.0.post20210125 

如果是python3.9，则是numba不兼容，安装log：Link requires a different Python (3.9.18 not in: '>=3.6,<3.9'): https://pypi.tuna.tsinghua.edu.cn/packages/46/e1/cbbc7c7967d9b10e54c852bf5bece0222a63bfb809d3354014c957ef1bda/numba-0.52.0.tar.gz#sha256=44661c5bd85e3d3619be0a40eedee34e39
7e9ccb3d4c458b70e10bf95d1ce933 (from https://pypi.tuna.tsinghua.edu.cn/simple/numba/) (requires-python:>=3.6,<3.9)

**Comment by only-someone** [comment]
i have the same problem and hope can give some steps to run successfully, thanks

**Comment by ZivDk** [comment]
i also have the same problem , and there are some other questions 

following is my error,please do me a favor, thanks

1. conda==4.10.3

ERROR: Ignored the following yanked versions: 3.0.6, 3.5.0, 3.7.0, 3.17.0, 4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.0.4, 4.0.5, 4.0.7, 4.0.8, 4.0.9, 4.1.2, 4.1.6, 4.2.6, 4.2.7, 4.3.13, 4.3.16
ERROR: Could not find a version that satisfies the requirement conda4.10.3 (from versions: none)
ERROR: No matching distribution found for conda4.10.3

2. conda-package-handling==1.7.3

ERROR: Could not find a version that satisfies the requirement conda-package-handling1.7.3 (from versions: 2.1.0, 2.2.0)
ERROR: No matching distribution found for conda-package-handling1.7.3

**Comment by QitaoZhao** [comment]
Hi, the `requirements.txt` has been updated. Can you try this?

**Comment by ZivDk** [comment]
i tried this again, and it works
thanks a lot
