### ISSUE TITLE
How to obtain the same experimental results as 47.9

### ISSUE THREAD

**Issue by lordTao2333** [QitaoZhao/PoseFormerV2#14]
I cannot obtain the same experimental result 47.9 using the parameters suggested by the author. Do you need to pay attention to any further experimental details? I hope the author can inform me.

**Comment by QitaoZhao** [comment]
For this model variant, you can set the learning rate to 8e-5. We may use different parameters for different model variants, but 8e-5 is experimentally a good starting point for you.

**Comment by tjdhg456** [comment]
Thank you for your works. 

In the Supplementary, learning rate is defined into 8e-4. Then, 8e-5 is better?

Also, what is the batch size for the paper settings.
Single gpu with batch size 1024? 

Again thank you for your innovative works.

**Comment by QitaoZhao** [comment]
8e-4 looks like a typo; we may correct it in the future paper version. We use a batch size of 512 for a single GPU.

**Comment by tjdhg456** [comment]
Thank you for your comment! I'll try it!!

**Comment by lordTao2333** [comment]
Thank you for your comment! I'll try it!!!!!
