### ISSUE TITLE
the PCK and AUC for MPI-INF-3DHP in PoseFormerV2

### ISSUE THREAD

**Issue by JihuaPeng** [QitaoZhao/PoseFormerV2#16]
First, thanks for your greatest work of PoseFormerV2. I checked your code and found that when evaluating the mpii dataset, the calculation of the two metrics pck and auc is not defined. May I know how to calculate the pck and auc for mpiinf-3dhp? Thanks a lot!

**Comment by QitaoZhao** [comment]
Thanks for your comments! We follow [P-STMO](https://github.com/paTRICK-swk/P-STMO) to set up mpi-inf-3dhp dataset. Since we just did some modifications, the code is not included in this repo.

**Comment by nxrcqupt01** [comment]
hello， where is the weights for PoseFormerV2 ?

**Comment by renwuliang** [comment]
Hello, can I replace the PCK function in your source code with a regular custom PCK function

**Comment by QitaoZhao** [comment]
Please check [here](https://github.com/QitaoZhao/PoseFormerV2/tree/main/mpi_inf_3dhp). I recently got the chance to upload the code. Sorry for the huge delay.
