### ISSUE TITLE
 About MFLOPs

### ISSUE THREAD

**Issue by pipilaser** [QitaoZhao/PoseFormerV2#17]
Hello, sir. May I inquire about the methodology you utilize to calculate the value of MFLOPs?

**Comment by QitaoZhao** [comment]
Hi, please check [ptflops](https://github.com/sovrasov/flops-counter.pytorch).

**Comment by pipilaser** [comment]
> Hi, please check [ptflops](https://github.com/sovrasov/flops-counter.pytorch).

How should I specify the input dimensions?
