### ISSUE TITLE
Joint and number

### ISSUE THREAD

**Issue by MWLLER** [QitaoZhao/PoseFormerV2#18]
Thank you for your excellent work. 
I encountered a problem while visualizing and obtaining the coordinates of each key point. Can I know what the joints corresponding to each keypoint are, and whether they are the same as those marked in the following figure.Thank you.
![b0e01ef8c24f089601be0213b300c9b](https://github.com/QitaoZhao/PoseFormerV2/assets/91045858/a68ed080-25e6-41c5-b05b-cad500d24a61)

**Comment by QitaoZhao** [comment]
Thanks for your kind comments! The joint format in your figure is correct.
