### ISSUE TITLE
Unable to reproduce the corresponding result in the article when the sequence length is 81, f=1, dct=3

### ISSUE THREAD

**Issue by zhaolengxiang** [QitaoZhao/PoseFormerV2#19]
I successfully reproduced the in-text accuracy for an input sequence of 27, f=1, dct=3, but when I raise the RF to 81, the MPJPE only reaches about 48.7. I have a learning rate of 0.0008 and a batchsize of 1024, what went wrong, any answer would be appreciated!

**Comment by zhaolengxiang** [comment]
有人和我有一样的问题吗?大佬教教我！

**Comment by ZivDk** [comment]
Under normal circumstances, it should be below 48.7, right?
how do you solve it
thanks

**Comment by zhaolengxiang** [comment]
> Under normal circumstances, it should be below 48.7, right?
> how do you solve it
> thanks 

I have successfully reproduced some of the results in this article. In my experience, getting the right results requires many trainings
