### ISSUE TITLE
parameters and FLOPs

### ISSUE THREAD

**Issue by Whj-cv** [QitaoZhao/PoseFormerV2#2]
Thank you very much for your work. I would like to know how the number of parameters and the amount of calculation of the model in your work is calculated?

**Comment by QitaoZhao** [comment]
Hello! Please refer to [here](https://github.com/QitaoZhao/PoseFormerV2/blob/main/run_poseformer.py#L203) for parameters. For FLOPs we use [ptflops](https://github.com/sovrasov/flops-counter.pytorch).

**Comment by Whj-cv** [comment]
> Hello! Please refer to [here](https://github.com/QitaoZhao/PoseFormerV2/blob/main/run_poseformer.py#L203) for parameters. For FLOPs we use [ptflops](https://github.com/sovrasov/flops-counter.pytorch).

Thank you very much for your answer! Can you provide the exact code for calculating the "FLOPs" and where to add them?

**Comment by Whj-cv** [comment]
> Hello! Please refer to [here](https://github.com/QitaoZhao/PoseFormerV2/blob/main/run_poseformer.py#L203) for parameters. For FLOPs we use [ptflops](https://github.com/sovrasov/flops-counter.pytorch).

Thank you very much, I have solved the problem.

**Comment by QitaoZhao** [comment]
Glad to hear that :)

**Comment by ZivDk** [comment]
> > Hello! Please refer to [here](https://github.com/QitaoZhao/PoseFormerV2/blob/main/run_poseformer.py#L203) for parameters. For FLOPs we use [ptflops](https://github.com/sovrasov/flops-counter.pytorch).
> 
> Thank you very much, I have solved the problem.

hello!  I would like to know how you solve the calculation of the model ?

i have some errors : 
Warning: module Dropout is treated as a zero-op.
Warning: module Attention is treated as a zero-op.
Warning: module Identity is treated as a zero-op.
Warning: module Mlp is treated as a zero-op.
Warning: module Block is treated as a zero-op.
Warning: module DropPath is treated as a zero-op.
Warning: module FreqMlp is treated as a zero-op.
Warning: module MixedBlock is treated as a zero-op.
Warning: module PoseTransformerV2 is treated as a zero-op.
Warning: module DataParallel is treated as a zero-op.

thanks for your help
