### ISSUE TITLE
Training code of 243 frames

### ISSUE THREAD

**Issue by vefalun** [QitaoZhao/PoseFormerV2#27]
Hello, thank you very much for your great work, I wanted to make sure that to train to get the best results mentioned in the paper, the training code is 
```
python run_poseformer.py -g 5 -k cpn_ft_h36m_dbb -frame 243 -frame-kept 27 -coeff-kept 27 -c checkpoint/243 -b 1024?
```

**Comment by QitaoZhao** [comment]
Thanks for your comments. Yes, the settings are correct, but I'm not really sure about the batch size. From my own experience, smaller batch sizes may give better results. If 1024 does not provide the expected performance, you can try reducing the batch size.
