### ISSUE TITLE
ModuleNotFoundError: No module named 'utils.transforms'

### ISSUE THREAD

**Issue by ZivDk** [QitaoZhao/PoseFormerV2#28]
When I enter this command :
python demo/vis.py --video sample_video.mp4

I will get the error like this :

Traceback (most recent call last):
  File "demo/vis.py", line 5, in <module>
    from lib.hrnet.gen_kpts import gen_video_kpts as hrnet_pose
  File "/home/dvlab/PoseFormerV2-main/demo/lib/hrnet/gen_kpts.py", line 21, in <module>
    from lib.hrnet.lib.utils.inference import get_final_preds
  File "/home/dvlab/PoseFormerV2-main/demo/lib/hrnet/lib/utils/inference.py", line 17, in <module>
    from utils.transforms import transform_preds
ModuleNotFoundError: No module named 'utils.transforms'

however, i download the whole file on the github. Also, I check if my document is missed, but everything is good 
please tell me how to solve this problem
thanks

**Comment by QitaoZhao** [comment]
Can you try the latest code? I did not encounter this issue.

**Comment by ZivDk** [comment]
it works, thanks a lot
