### ISSUE TITLE
I don't know how to make Figure 5

### ISSUE THREAD

**Issue by ZivDk** [QitaoZhao/PoseFormerV2#29]
![image](https://github.com/QitaoZhao/PoseFormerV2/assets/92445133/241c1702-cb58-4d63-8952-e9488676aa0c)

I'm having difficulty understanding what each point on the figure indicates. For example, why does PoseFormerV2 27xRF have three points? Was this data mentioned in the paper?

Also, under what conditions does PoseFormerV2 9xRF have an MPJPE of 46?"

if i can jump into conclusion . most of all , the PoseFormerV2 27xRF is the best model except for PoseFormerV2 9xRF with MPJPE of 46
PoseFormerV2 9xRF with MPJPE of 46  is the special case ?

Thank you for your reply

**Comment by QitaoZhao** [comment]
Thanks for your comments! "27xRF" means the ratio between the total sequence length and the number of frames we keep (in spatio-temporal modeling) is 27. Therefore, we can obtain a series of points on the curve by varying the total sequence length.

"9xRF" PoseFormerV2 has an MPJPE of 46 using 81 total video frames (while keeping 9 in spatio-temporal modeling; you can check `Tab. 2` in the paper). By increasing the number of this ratio, we expect the model to gain from the larger temporal receptive field. However, it seems to meet its bottleneck when the total sequence number is huge (especially when the ratio is 27). This phenomenon is under-explored during our submission. So, we do not include more points on the "27xRF" curve in the figure. We also report the performance of "9xRF" with 243 total video frames in `Tab. 2` (45.2 MPJPE).

**Comment by ZivDk** [comment]
I really appreciate your response! However, I still have some questions about Figure 5.

The description in Figure 5 states: 'RF: Receptive Field and k×RF indicates that the RF of PoseFormerV2 is expanded by k times with a few low-frequency DCT coefficients of the full sequence.' Additionally, as mentioned previously in the paper, 'If not specified, we simply set n = f for convenience.'

Based on this, can I comprehend that by assuming n = f, the statement "  '27xRF' means the ratio between the total sequence length and the number of frames retained (in spatio-temporal modeling) is 27. "
conveys the same meaning as the statement 'RF: Receptive Field and k×RF indicates that the RF of PoseFormerV2 is expanded by k times with a few low-frequency DCT coefficients of the full sequence.' ?

Furthermore , what does the point "27xRF" with 200 MFLOPs stand for ? 
 I seem to be unable to find the information in`Tab.2`

Thanks for your help

**Comment by QitaoZhao** [comment]
1) Yes, and I'm sorry for the confusion. The two statements are exactly the same. 
2) For the "27xRF" variant with 200 MFLOPs, my best guess is the model with 135 or 189 frames (can't remember the exact number) in total. Because it's not a "neat" and "standard" setting, we do not include it in `Tab. 2`.

**Comment by ZivDk** [comment]
Thank you very much for your explanation.
It really helps me a lot
