### ISSUE TITLE
Replication of Poseformer V1 and MixSTE experiments

### ISSUE THREAD

**Issue by Lzh-Code-lab** [QitaoZhao/PoseFormerV2#3]
Great innovation. I noticed that the PoseFormer V1 experiment you replicated had a much better performance compared to the original article, while the MixSTE experiment had a significant decrease in performance. Is this a normal phenomenon?

**Comment by QitaoZhao** [comment]
Thanks for your interest! Can you specify the table/figure you refer to?

**Comment by Lzh-Code-lab** [comment]
PoseFormerV1 Table 3 (input 9 frames on MPIINF-3DHP), PCK:88.6; AUC: 56.4; MPJPE: 77.1.

**Comment by Lzh-Code-lab** [comment]
PoseFormerV2 Table 3 (PoseFormerV1 input 9 frames on MPIINF-3DHP), PCK:95.4; AUC: 63.2; MPJPE: 57.7.

**Comment by QitaoZhao** [comment]
Thanks. We did reproduce PoseFormerV1 but _not_ reproduce MixSTE on MPI dataset. The reproduced PoseFormerV1 result (AUC & MPJPE) is worse than MixSTE, which is consistent with Human3.6M.

**Comment by Lzh-Code-lab** [comment]
MixSTE Table 5 (on Human3.6M), MPJPE: 40.9mm; PoseFormerV2 Table 2 (on Human3.6M), best MPJPE: 45.2mm

**Comment by QitaoZhao** [comment]
Please note the frame number. We compare results with similar computation.

**Comment by Lzh-Code-lab** [comment]
> Thanks. We did reproduce PoseFormerV1 but _not_ reproduce MixSTE on MPI dataset. The reproduced PoseFormerV1 result (AUC & MPJPE) is worse than MixSTE, which is consistent with Human3.6M.

In PoseFormerV2 Table 3, reproduce PoseFormerV1 is better than MixSTE

**Comment by Lzh-Code-lab** [comment]
> Please note the frame number. We compare results with similar computation.

Thank you for your answer. MixSTE does not mention how many frames are used as input, but it can be seen from PoseFormer Table 2 that the computational cost of MixSTE with 3 input frames is much higher than that of PoseFormer with 243 input frames.
