### ISSUE TITLE
some confusion about the figure of network structure

### ISSUE THREAD

**Issue by ZivDk** [QitaoZhao/PoseFormerV2#31]
![image](https://github.com/QitaoZhao/PoseFormerV2/assets/92445133/13f436be-41a4-4370-9ed7-266c4212a8a0)

If I remember correctly, you took the structure of the PoseformerV1 spatial-temporal transformer and replaced the temporal transformer with a "DCT + LPF + Linear projection" module, right?

I'm curious why only the spatial transformer part has temporal embedding instead of spatial embedding.
Is it related to "reformulated as a Time-Frequency Feature Fusion module"? So it must have temporal embedding.
Please help me figure this out.

Thanks for your reply

**Comment by QitaoZhao** [comment]
Thanks for your question. If you look at here
https://github.com/QitaoZhao/PoseFormerV2/blob/0c0b1252f6ce722ed621d82b551362f25a023285/common/model_poseformer.py#L204
We indeed have spatial embedding for each joint in Spatial Transformer. This design follows PoseFormer(V1).

**Comment by ZivDk** [comment]
thank you very much
