### ISSUE TITLE
I'm confused about Code

### ISSUE THREAD

**Issue by ZivDk** [QitaoZhao/PoseFormerV2#32]
https://github.com/QitaoZhao/PoseFormerV2/blob/0c0b1252f6ce722ed621d82b551362f25a023285/common/model_poseformer.py#L224

https://github.com/QitaoZhao/PoseFormerV2/blob/0c0b1252f6ce722ed621d82b551362f25a023285/common/model_poseformer.py#L120

https://github.com/QitaoZhao/PoseFormerV2/blob/0c0b1252f6ce722ed621d82b551362f25a023285/common/model_poseformer.py#L122

https://github.com/QitaoZhao/PoseFormerV2/blob/0c0b1252f6ce722ed621d82b551362f25a023285/common/model_poseformer.py#L127

https://github.com/QitaoZhao/PoseFormerV2/blob/0c0b1252f6ce722ed621d82b551362f25a023285/common/model_poseformer.py#L128
`x[:, :f//2]` `x[:, f//2:]` Are the frame numbers of x set incorrectly, or did I misunderstand?
x combine with  Spatial_feature , does x belongs to the `x[:, :f//2]`, and Spatial_feature belongs to the `x[:, f//2:]`.?

thanks for your help

**Comment by SJM0018** [comment]
I have the same question as you！！！

**Comment by ZivDk** [comment]
> I have the same question as you！！！

have you tried to reverse them, and checked  the result?

**Comment by SJM0018** [comment]
> > I have the same question as you！！！
> 
> have you tried to reverse them, and checked the result?

No, I don't do it in PoseFormerV2. But I reversed it to be consistent with the paper in my own model. The result turned out to be better.

**Comment by QitaoZhao** [comment]
Perhaps the name of `FreqMLP` is a bit confusing. We meant to use this module for the time-domain feature to minor the domain gap. Please leave comments if you have further questions.

**Comment by ZivDk** [comment]
thank you very much . It's clear
