### ISSUE TITLE
How to check the robustness of a model

### ISSUE THREAD

**Issue by SJM0018** [QitaoZhao/PoseFormerV2#33]
Great work！And I want to know how to add noise to test the robustness of the model, like Figure 6 in your paper. Thank you！！！

**Comment by SJM0018** [comment]
<img width="997" alt="image" src="https://github.com/QitaoZhao/PoseFormerV2/assets/101796109/f3300434-a332-4e8b-ab33-0f326ad7c698">
Are these lines of code in run_poseformer.py?

**Comment by QitaoZhao** [comment]
Thanks for your comments. 
Yes, exactly. We vary the `std` of Gaussian noise to measure the performance degradation.

**Comment by SJM0018** [comment]
@QitaoZhao What is the general range of std? In your paper, is std=3,5,8,10?

**Comment by QitaoZhao** [comment]
Yes.
