### ISSUE TITLE
Some confusion about run_poseformer.py

### ISSUE THREAD

**Issue by OliverSTH** [QitaoZhao/PoseFormerV2#34]
Accroding to run_poseformer.py
line 287 and line 337 "inputs_3d[:, :, 0] = 0"

What does "inputs_3d[:, :, 0] = 0" mean?
The performance is worse after taking it out, but I can't understand it, it doesn't seem to have anything to do with the training model, I just know that the "MPJPE" calculated this way is not the same.

Thank you for your reply.

**Comment by QitaoZhao** [comment]
The model predicts the joint coordinates w.r.t. the "hip", so we manually set its coordinate to zero and shift other joints accordingly.

**Comment by OliverSTH** [comment]
Thanks for your previous reply.
But I still have two questions to ask you.

I understand setting the "hips" as the origin in three-dimensional space, but for the other joint points, is there a script where you perform the shift? 

The second question is, in your response, you mentioned that the model can predict the coordinates of other joint points w.r.t the "hips" (including the hips). Shouldn't the "hips" joint point be the origin in three-dimensional space in this case? Why isn't it printed out like that, or have you implemented this functionality in another script?

predicted =  torch.tensor([[-0.6461, -0.8373,  0.2719],
        [-0.2475,  0.3515,  0.5209],
        [-0.4183,  0.3455,  0.5940],
        [-0.1337, -0.2788,  0.0038],
        [-0.3952,  0.1466,  0.3489],
        [ 0.1195,  0.1373,  0.0263],
        [-0.2638, -0.4917,  1.0485],
        [ 0.2197, -0.3982,  0.2207],
        [-0.1862,  0.2375,  0.3127],
        [-0.6661,  0.1557, -0.1037],
        [ 1.1163, -0.2160, -0.0959],
        [-0.7857, -0.0244, -0.1718],
        [ 0.9798,  0.3071, -1.0460],
        [ 0.6979,  0.2977,  1.0907],
        [-0.2004,  0.1811, -0.0954],
        [-0.1286, -0.0903, -0.0829],
        [ 0.7842,  1.1195, -1.0250]])
target = torch.tensor([[ 0.0000,  0.0000,  0.0000],
        [ 0.1109, -0.0413,  0.0668],
        [ 0.0642,  0.4002,  0.1314],
        [ 0.0877,  0.8368,  0.1066],
        [-0.1109,  0.0413, -0.0668],
        [-0.1991,  0.3714,  0.2239],
        [-0.0394,  0.7560,  0.0881],
        [-0.0310, -0.1997, -0.1017],
        [-0.0759, -0.4349, -0.1905],
        [-0.0547, -0.5241, -0.1351],
        [-0.0838, -0.5916, -0.2235],
        [-0.1731, -0.3410, -0.2259],
        [-0.2355, -0.0740, -0.1983],
        [-0.2072, -0.1597,  0.0320],
        [ 0.0560, -0.4368, -0.1445],
        [ 0.2722, -0.3525,  0.0041],
        [ 0.3490, -0.5192,  0.1698]])

Thank you for your response.

**Comment by QitaoZhao** [comment]
1. We shifted the joints in pre-processing: https://github.com/QitaoZhao/PoseFormerV2/blob/0c0b1252f6ce722ed621d82b551362f25a023285/run_poseformer.py#L71
2. Although we enforced the hip's coordinate to be the origin in our training target, the model does not necessarily know this (its coordinate is not really 0 but should be quite close to 0 as the training progresses).

**Comment by OliverSTH** [comment]
Thank you for your reply.
