### ISSUE TITLE
Questions about the results of StridedTrans. in Experiment Table 2

### ISSUE THREAD

**Issue by wileychan** [QitaoZhao/PoseFormerV2#35]
I noticed in Table 2 that _StridedTrans.[15] TMM’22_ has an MPJPE of **47.5** and MFLOPs of 342.5. This is far from the results reported in the StridedTrans. article. In the StridedTrans. author's article, an input of 81 frames can reach 45.4 MPJPE. The input of 27 frames can reach 46.9MPJPE and only requires 128MFLOPs.
Can you explain why you chose the result 47.5?
Thanks!

Figure 1： Table 2 in your paper.
![image](https://github.com/QitaoZhao/PoseFormerV2/assets/62558932/e649a651-7b73-4e83-b35f-0c10ee5667c0)

Figure 2:  Table in StridedTrans. author's article
![image](https://github.com/QitaoZhao/PoseFormerV2/assets/62558932/eae19f70-1919-4178-94ae-aeb6a0c36ddd)

**Comment by QitaoZhao** [comment]
The authors mentioned in `B. Implementation Details` that they used a refinement model. To ensure a fair comparison, we re-ran the model without refinement and reported the results we reproduced.

**Comment by wileychan** [comment]
Thanks for your reply, my question has been answered.
