### ISSUE TITLE
MPI-INF-3DHP数据集下运行结果中的p1指的是什么

### ISSUE THREAD

**Issue by HL-KL** [QitaoZhao/PoseFormerV2#38]
![123](https://github.com/QitaoZhao/PoseFormerV2/assets/49120471/2061e5da-8dc1-43bb-a360-33274c83c019)
在该数据集下MPI-INF-3DHP进行的复现结果中P1指的是什么

**Comment by QitaoZhao** [comment]
P1指Protocol 1，也就是evaluation的MPJPE。
