### ISSUE TITLE
为什么训练Human3.6M数据集的模型代码和训练MPI-INF-3DHP数据集模型代码不同

### ISSUE THREAD

**Issue by HL-KL** [QitaoZhao/PoseFormerV2#39]
为什么训练Human3.6M数据集的模型代码和训练MPI-INF-3DHP数据集模型代码不同

**Comment by QitaoZhao** [comment]
我们主要参考[P-STMO](https://github.com/paTRICK-swk/P-STMO)来准备我们的代码，抱歉没有统一两个数据集。
