### ISSUE TITLE
Runtime issues

### ISSUE THREAD

**Issue by haofeng0705** [QitaoZhao/PoseFormerV2#5]
Great work！The utilization rate of the GPU is very low when I am running. How should I modify the config?

**Comment by QitaoZhao** [comment]
Thanks for your interest in our work! Consider increasing the _batch size_, the _number of used frames_, and _the number of kept frequency coefficients_. Generally, large memory costs introduce high GPU utility.

This is also related to our codebase, which is relatively old. We may improve it in the future version.

**Comment by haofeng0705** [comment]
Is the utilization of this GPU normal by default?
<img width="849" alt="image" src="https://user-images.githubusercontent.com/30925823/235866329-09fa0302-d916-46f0-bed3-e3f14ec4edba.png">

**Comment by QitaoZhao** [comment]
Fluctuations may occur in the training process. However, if it keeps 0%, it is not normal. You can check which part is the bottleneck causing slow training.
