### ISSUE TITLE
ONNX export

### ISSUE THREAD

**Issue by leonid-pishchulin** [QitaoZhao/PoseFormerV2#6]
could you provide a script to export model to ONNX, please?

**Comment by QitaoZhao** [comment]
I may do this soon as I am currently busy with some stuff.

**Comment by noahcoolboy** [comment]
Hi Leonid
It is not currently possible to convert these models to onnx
I have attempted to do so, but it seems that there are some torch operators used by this model which are not yet supported for the conversion

Placing the following line under `model.eval()`
`torch.onnx.export(model.module, torch.randn(1, args.frames, args.n_joints, 2).cuda(), "poseformer.onnx", verbose=True, opset_version=17)`
Will cause an error: `torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::fft_fft' to ONNX opset version 17 is not supported.`

Conversion will probably become possible, once this issue gets closed:
https://github.com/pytorch/pytorch/issues/81075

If you do have a solution, or have been able to convert it, please do tell me as I am trying to do the same
Thank you
