### ISSUE TITLE
the file "torch_dct" NotFound

### ISSUE THREAD

**Issue by psile** [QitaoZhao/PoseFormerV2#7]
Hello, Great work! but I can not find the torch_dct file,can you upload it? Thank you a lot!

**Comment by QitaoZhao** [comment]
Thanks for your interest. Please check https://github.com/zh217/torch-dct for the package. I will make this clear soon in README.

**Comment by psile** [comment]
Thanks a lot, I think there is no difference between the code 

def get_dct_matrix(N):
    dct_m = np.eye(N)
    
    for k in np.arange(N):
        for i in np.arange(N):
            w = np.sqrt(2 / N)
            if k == 0:
                w = np.sqrt(1 / N)
            dct_m[k, i] = w * np.cos(np.pi * (i + 1 / 2) * k / N)
    idct_m = np.linalg.inv(dct_m)
    return dct_m, idct_m

and torch_dct?

Thanks a lot again.

**Comment by QitaoZhao** [comment]
Iterations (e.g., for k in xxx) may cause slow speed, hence I recommend you to check their implementation!

**Comment by psile** [comment]
OK, I got it! Thansks a lot again!
