### ISSUE TITLE
Inference on custom videos

### ISSUE THREAD

**Issue by elena-andreini** [QitaoZhao/PoseFormerV2#8]
Thank you for your work ! Are the released pretrained models suitable for inference on custom videos ? Or for the demos do you use models trained differently ? Thanks !

**Comment by elena-andreini** [comment]
The pretrained models give the expected results when used for inference on custom videos. I used the code from https://github.com/zczcwh/poseformer_demo, based in turn on https://github.com/Vegetebird/MHFormer, with minor adaptations.

**Comment by QitaoZhao** [comment]
I'm glad to hear that!

**Comment by ovshake** [comment]
Can you please let me know what minor adaptations you did to get it running? I am struggling with getting poseformer v2 model running on custom videos.

**Comment by QitaoZhao** [comment]
> Can you please let me know what minor adaptations you did to get it running? I am struggling with getting poseformer v2 model running on custom videos.

We have released codes for video demo inference. Please check them!
