### ISSUE TITLE
About MPI-INF-3DHP 

### ISSUE THREAD

**Issue by jischeng** [QitaoZhao/PoseFormerV2#9]
Thanks for your awesome work. I also hope to use the MPI-INF-3DHP data set in my experiment.
How did you deal with MPI-INF-3DHP? 
This problem has been bothering me for several days. 

I would be very glad if you could help me.

**Comment by QitaoZhao** [comment]
Thanks for your interest! Please refer to [P-STMO](https://github.com/paTRICK-swk/P-STMO). We also follow their implementations.

**Comment by Aerikervalid** [comment]
> Thanks for your awesome work. I also hope to use the MPI-INF-3DHP data set in my experiment. How did you deal with MPI-INF-3DHP? This problem has been bothering me for several days.
> 
> I would be very glad if you could help me.

Hi, Have you solved the problem?
Like you，This problem has been bothering me for several days .

**Comment by LYee0515** [comment]
> 感谢您的出色工作。我还希望在我的实验中使用 MPI-INF-3DHP 数据集。您是如何处理MPI-INF-3DHP的？这个问题已经困扰了我好几天了。
> 
> 如果你能帮助我，我会很高兴。
Hi, Have you solved the problem?
Like you，This problem has been bothering me for several days .

**Comment by HL-KL** [comment]
> 感谢您的关注！请参阅[P-STMO。](https://github.com/paTRICK-swk/P-STMO)我们也遵循他们的实施。

您好方便给出根据P-STMO修改的相关代码吗，具体实现细节吗，我们希望在MPI-INF-3DHP 数据集上进行实验，如果方便的话可以通过邮箱（2540610633@qq.com）发一下吗

**Comment by HL-KL** [comment]
> 感谢您的出色工作。我还希望在我的实验中使用 MPI-INF-3DHP 数据集。您是如何处理MPI-INF-3DHP的？这个问题已经困扰了我好几天了。
> 
> 如果你能帮助我，我会很高兴。

请问你解决了吗，方便分享下在MPI-INF-3DHP数据集上进行实验的相关代码吗，我的邮箱（2540610633@qq.com）,感激不尽

**Comment by QitaoZhao** [comment]
Please check [here](https://github.com/QitaoZhao/PoseFormerV2/tree/main/mpi_inf_3dhp) (@HL-KL). I recently got the chance to upload the code. Sorry for the huge delay.
